name = "Hugoplate"
license = "MIT"
licenselink = "https://github.com/zeon-studio/hugoplate/blob/main/LICENSE"
description = "Hugoplate is a free starter template built with Hugo, and TailwindCSS, providing everything you need to jumpstart your Hugo project and save valuable time."
homepage = "https://github.com/zeon-studio/hugoplate"
demosite = "https://zeon.studio/preview?project=hugoplate"
min_version = "0.151.0"

tags = [
  "lighting",
  "television",
  "events",
  "corporate",
  "shows",
  "music",
]

features = [
  "Search",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "LightingDir.com"
homepage = "https://www.lightingdir.com"

[original]
author = "LightingDir.com"
homepage = "https://www.lightingdir.com"
repo = "https://www.lightingdir.com"
